// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJfwTX3d9b-LffBwIFaH5HL7W-cuXwZoE',
    appId: '1:1034519442445:web:9b547e056332bab1f09144',
    messagingSenderId: '1034519442445',
    projectId: 'creditrack-5d338',
    authDomain: 'creditrack-5d338.firebaseapp.com',
    storageBucket: 'creditrack-5d338.appspot.com',
    measurementId: 'G-7C65LT0C3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcgwgaEJ8a04VpGa8-3Cxi7sprjzHhEAc',
    appId: '1:1034519442445:android:1ba362c46477fc94f09144',
    messagingSenderId: '1034519442445',
    projectId: 'creditrack-5d338',
    storageBucket: 'creditrack-5d338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8mopW9uwyyY-GfCH6A12XYAa5dwLcrio',
    appId: '1:1034519442445:ios:d89be5c3c8edf1eaf09144',
    messagingSenderId: '1034519442445',
    projectId: 'creditrack-5d338',
    storageBucket: 'creditrack-5d338.appspot.com',
    iosBundleId: 'com.example.creditrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8mopW9uwyyY-GfCH6A12XYAa5dwLcrio',
    appId: '1:1034519442445:ios:7950b88c8a0abf40f09144',
    messagingSenderId: '1034519442445',
    projectId: 'creditrack-5d338',
    storageBucket: 'creditrack-5d338.appspot.com',
    iosBundleId: 'com.example.creditrack.RunnerTests',
  );
}
